on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "develop"
name: test
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # - uses: actions/setup-go@v3
            #   with:
            #       go-version: ">=1.18"
            # - uses: actions/checkout@v3

            - uses: actions/checkout@v3

            # go.mod ファイルからGoのバージョンを抽出する
            - name: Extract Go version from go.mod
              run: echo "::set-output name=go_version::$(grep -oP '^go \K[\d.]+?' go.mod)"

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: ${{ steps.extract_go_version.outputs.go_version }}

            - run: go test ./... -coverprofile=coverage.out
            - name: report coverage
              uses: k1LoW/octocov-action@v0
